### ISSUE TITLE
app try to translate 

### ISSUE THREAD

**Issue by garrick11** [Romanysoft/Try-to-translate#1]
I CAN COPY AND PASTE ON MY MAC BOOK PRO,,,YOUR APP WILL NOT LET ME COPY OR PASTE INTO ANY OF MY APPLICATIONS,,,(NOTES,PAGES,EMAIL)

**Comment by jetiny8** [comment]
You can use command+c and command+v to copy and paste, maybe it is not enough for you ?

**Comment by garrick11** [comment]
Thank you,,,

Mr.Garrick Elliston

**Comment by jetiny8** [comment]
I'm very glad to serve you.
