### ISSUE TITLE
"Try to Translate" worked fine, but STOOPED WORKING on all computers

### ISSUE THREAD

**Issue by Wayne-Ellsworth** [Romanysoft/Try-to-translate#2]
"Try to Translate" worked fine, but STOOPED WORKING on all computers.

It was our favorite translator! Please fix!

Thank you,

wayne@icajapan.org

**Comment by lauer3912** [comment]
Dear Wayne-Ellsworth,

Thank you for contacting us.
Try to Translate is based on google translate API, you have to check
whether you can directly access https://translate.google.com

Look forward to your feedbacks and suggestions soon

RomanySoft LAB. Ian

2015-07-28 18:19 GMT+08:00 Wayne-Ellsworth notifications@github.com:

**Comment by EmmanuelStreiff** [comment]
hello ! the same problem for me :(( 
It's not normal to be obliged to go to the "translate.google.com" !
We are several who have spend money for the "Try to translate" on the AppStore...so thanks to repair this bug !
Emmanuel

**Comment by Wayne-Ellsworth** [comment]
Sure, we can use the much poorer interface and inconvenient "translate.google.com", but I don't use it any more. There are abundant options available. If I had spare time, I would create a lawsuit against google, but I would loose even more than the perfect "Try to translate".

How can Google infringe upon our privacy, and Apple's privacy? Now Google jumps on my MAC Desktop every hour. STOP. STOP. STOP.
