### ISSUE TITLE
Try to Translate worked for months now it does not works

### ISSUE THREAD

**Issue by joacofab** [Romanysoft/Try-to-translate#3]
Hi.
For months Try to Translate worked really nice, however since yesterday I am getting a message that I am not connected to internet, if that would be the case then I could not write to you, right? 

I am using a Mac with OS 10.10.4

Thanks, Joaquin

**Comment by lauer3912** [comment]
Dear Joaquin,

Thank you for contacting us.
Try to Translate is based on google translate API, you have to check
whether you can directly access https://translate.google.com

Look forward to your feedbacks and suggestions soon

RomanySoft LAB. Ian

__

2015-07-29 22:23 GMT+08:00 joacofab notifications@github.com:

**Comment by jodec** [comment]
Hallo

I have the same problem as my predecessor Joaquin. I had directly access to the google translate site and the translation was successful. What must I do to have my app(Try to translate) on my computer working successful again? I am working with a Mac computer with Safari. Thank you kindly.

**Comment by EmmanuelStreiff** [comment]
hello ! the same problem for me :(( 
It's not normal to be obliged to go to the "translate.google.com" !
We are several who have spend money for the "Try to translate" on the AppStore...so thanks to repair this bug !
Emmanuel
